### ISSUE TITLE
label DN categories in getColor action

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#14]
take a look at the colors in the Board that I just pushed. I was thinking we could swap temperate and tropical. Did you pick the colors for each category using the paper? Or was this just something you decided.

**Comment by dktaylor916** [comment]
I did originally use the same colors that were used in the paper, but i think there is no problem in switching them.

**Comment by dktaylor916** [comment]
as far as the colors on the map they were the same. but i assume we want the colors of the map to match the colors of the board?

**Comment by matthewfdaniels** [comment]
if you can label what each of the DN categories are,  I can carry over the
colors

**Comment by dktaylor916** [comment]
great. getColor.js and getColorSimp.js now have all the labels with their DN value

**Comment by dktaylor916** [comment]
I went ahead and swapped over the colors and filled in the gaps where we needed new ones. we can have a look at it toghether later today?
