### ISSUE TITLE
popup border is missing on arrow (see image)

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#16]
<img width="446" alt="image" src="https://github.com/the-pudding/climate-zones/assets/2880174/d3d405c1-6587-44e0-8231-4df6ac4af41d">

**Comment by dktaylor916** [comment]
<img width="560" alt="Screenshot 2024-06-13 at 15 48 32" src="https://github.com/the-pudding/climate-zones/assets/39200183/531934dc-88d5-41c0-b420-dee715401f25">

made pointer light grey. think this works alright?
