### ISSUE TITLE
team feedback

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#17]
**Alvin**

- The very first sentence is slightly clunky to read, and the second one feels like a non sequitor.  "Climate change is often spoken about in terms of total earth warming, sea-level rise, and natural disasters. But unless you are a climate scientist, a two degree rise in temperature may not be helpful in providing a tangible vision of our future.”
    - One suggestion is to just have a sentence like: “Climate scientists say that we’re headed for more than a two degree rise in earth’s temperatures. But for most of us, that’s not really helpful in providing a tangible vision of our future.”
- “In order to distinguish the difference within these categories, there are 30 subcategories that help give more insight into the relative climates within each classification.” – I think only seeing four subcategories on the map with this text is slightly confusing. Maybe in this slide, just say: “To distinguish the differences within these categories, they are divided into subcategories. For example, for temperate zones are split up into these four subcategories.”
    - Then intro the 30 in the next slide
- This sentence is missing periods so I didn’t realize it was three separate things: “Temperate climates shifting north Tropical and Arid climates growing Cold climates dissapearing.”
    - Spelling on “disappearing” is wrong above
- I know you’re looking through colors, so please ignore if this is on your list. The green hues are really tough for me to see on the scrolly legend and then match up w/ the map. (I typically have a tough time seeing differences in greens, fwiw.)
- I love the way the classification list looks on mobile.
- The classification list (starting with “Hollywood becomes Bollywood”) it feels like the animation is triggered a bit late on the scrolly, especially since there’s a reset animation first and then the cities move.
- For this classification section, I didn’t understand what it meant for cities to be “Cold” or “Temperate” – maybe consider a very short description right under the name? Or add the descriptor in the scrolly text?
    - OHHHH – I didn’t realize I could hover on the names for descriptions. Some indicator of this would be nice.
        - Some of the tooltips don’t fit on the page.
        
        ![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/8edfa99c-af99-4353-b217-e5b3c5da3a34/e17bd5ad-4abd-4e30-aa18-434483a2f807/Untitled.png)
        
- The “Explore” section confused me a bit. One thing that might make that clearer/more punchy is to have a sentence that pops up after you click on a city that says something like: “New York is currently in the COLD climate zone. In 2070, it is projected to be TEMPERATE because X and Y.”
    - In addition, I kinda want those dotted lines back here.

**Comment by matthewfdaniels** [comment]
fixed the dotted lines on the explore section

**Comment by dktaylor916** [comment]
updated the text

**Comment by dktaylor916** [comment]
I really like that idea of adding a text box that has a short blurb about where the city moves to. Working on this today

**Comment by dktaylor916** [comment]
^^^ completed and pused now

**Comment by dktaylor916** [comment]
^^ completed and pushed now
