### ISSUE TITLE
author bio

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#19]
can you send me a bio that you want to use? something like this:
https://pudding.cool/author/chris-dalla-riva/

**Comment by dktaylor916** [comment]
Derek Taylor is a geospatial data scientist and data viz enthusiast. He loves all things maps and code. Check some of his other work [here](https://dktaylor916.github.io/portfolio/)

**Comment by dktaylor916** [comment]
Also - i'm not sure what the policy is at the pudding, but i do feel like we should share the by-line. this has very much felt like a collaboration on this story!
