### ISSUE TITLE
on mobile, the main classification of Cold's label is too high, but when lowered the z-index is a bit screwy and appears below text 

### ISSUE THREAD

**Issue by dktaylor916** [the-pudding/climate-zones#23]
<img width="434" alt="Screenshot 2024-06-16 at 18 30 43" src="https://github.com/the-pudding/climate-zones/assets/39200183/323d3d3c-2d60-4ebc-9b0a-c648c0898352">

**Comment by matthewfdaniels** [comment]
you might just need to force the z-axis higher on the tooltip, but this might be a function of just the mobile layers being weird (which sometimes happens). try giving the labels an explicit z-axis?

**Comment by dktaylor916** [comment]
yup, had to play around a lot with mobile specific z-index's but all looks good now
