### ISSUE TITLE
short phones result in clutter with pop up

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#25]
iphone 13 mini

![image](https://github.com/the-pudding/climate-zones/assets/2880174/401b9141-22be-450d-b493-f2478f507dfa)

**Comment by dktaylor916** [comment]
hmm okay, maybe for screen sizes with smaller width that can be a popup that can be closed?

**Comment by dktaylor916** [comment]
<img width="446" alt="Screenshot 2024-06-18 at 17 37 38" src="https://github.com/the-pudding/climate-zones/assets/39200183/e782db17-65de-4718-89ce-c83614bd9b30">
Thoughts on this? i have it switch for max-height:800px

**Comment by dktaylor916** [comment]
thinking it might work because nothing goes into Cold zones

**Comment by matthewfdaniels** [comment]
I just repositioned the pop up as relative on short phones, so hopefully this works!
