### ISSUE TITLE
can you confirm that the "before" climate classifications are for the year 2023 and not earlier? the study is from 2018 so...

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#26]

**Comment by dktaylor916** [comment]
Ah yeah, I think when saw this  _'We present new global maps of the Köppen-Geiger climate classification at an unprecedented 1-km resolution for the present-day **(1980–2016)** and for projected future conditions **(2071–2100)** under climate change. '_  i just wanted to simplify the dates a bit, and took current day as that data could represent 2023 as well. Though perhaps this is too much of a jump. What would your call be?

**Comment by matthewfdaniels** [comment]
Let's replace "2023" with "Present Day"

**Comment by dktaylor916** [comment]
Got it
