### ISSUE TITLE
check site in safari/firefox

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/climate-zones#8]

**Comment by dktaylor916** [comment]
Firefox:
- [x]  **break after : columns not working**
- [ ] Pudding header not showing

Safari:
- [x] Pudding header not showing
- [x] Text starts behind map
- [x] **Scrolly freaks out between value 7 and 8**
- [x] The borders dont change on the labels
- [x] **The lines that draw in between labels are off**

**Comment by dktaylor916** [comment]
heres a list i put together of things to fix on the various browsers. Ones in bold ive put some time into and cant seem to figure out. maybe you can assist on those?

**Comment by matthewfdaniels** [comment]
yea totally. ill start a branch.

**Comment by dktaylor916** [comment]
great! thanks so much, let me know if you need any clarificaiton. I'll have some time this afternoon to work on this as well. then all day tomorrow

**Comment by dktaylor916** [comment]
sorry just realized i hadnt pushed most recent changes, but now it should be up to date

**Comment by dktaylor916** [comment]
hey matt, just a heads up, ive fixed all the firefox issues, so now focusing on safari
